import './sass/main.scss';
import './js/mobile-menu';
import './js/book-categories';
import './js/support.js';
import './js/books-gallery';
import './js/modal-registration';
import './js/shopping-list';
import './js/firebase';
import './js/scroll-up';